import Foundation
// swiftlint:disable:next blanket_disable_command
// swiftlint:disable line_length

public struct SwiftCodeEmitter: SwiftSourceEmitter {
    public init() {}

    public func emit(ir: SOAPCodeGenerationIR, syntaxProfile: CodeGenerationSyntaxProfile) -> String {
        var lines: [String] = []
        lines.append("import Foundation")
        lines.append("import SwiftSOAPCore")

        if ir.generationScope.contains(.client) {
            if ir.runtimeTargets.contains(.async) {
                lines.append("import SwiftSOAPClientAsync")
            }
            if ir.runtimeTargets.contains(.nio) {
                lines.append("import NIOCore")
                lines.append("import SwiftSOAPClientNIO")
            }
        }

        if ir.generationScope.contains(.server) {
            if ir.runtimeTargets.contains(.async) {
                lines.append("import SwiftSOAPServerAsync")
            }
            if ir.runtimeTargets.contains(.nio) {
                lines.append("import NIOCore")
                lines.append("import SwiftSOAPServerNIO")
            }
        }

        lines.append("")
        lines.append("// Generated by SwiftSOAPCodeGen. Do not edit manually.")
        lines.append("// Target Swift version: \(syntaxProfile.targetSwiftVersion.description)")
        lines.append("")

        for generatedType in ir.generatedTypes {
            lines.append(contentsOf: emitType(generatedType, validationProfile: ir.validationProfile))
            lines.append("")
        }

        for service in ir.services {
            for port in service.ports {
                for operation in port.operations {
                    lines.append(contentsOf: emitOperationContract(operation))
                    lines.append("")
                }
            }
        }

        if ir.generationScope.contains(.client) {
            if ir.runtimeTargets.contains(.async) {
                lines.append(contentsOf: emitAsyncClients(ir.services, syntaxProfile: syntaxProfile))
                lines.append("")
            }

            if ir.runtimeTargets.contains(.nio) {
                lines.append(contentsOf: emitNIOClients(ir.services, syntaxProfile: syntaxProfile))
                lines.append("")
            }
        }

        if ir.generationScope.contains(.server) {
            if ir.runtimeTargets.contains(.async) {
                lines.append(contentsOf: emitAsyncServers(ir.services, syntaxProfile: syntaxProfile))
                lines.append("")
            }

            if ir.runtimeTargets.contains(.nio) {
                lines.append(contentsOf: emitNIOServers(ir.services, syntaxProfile: syntaxProfile))
                lines.append("")
            }
        }

        return lines.joined(separator: "\n")
    }

    private func emitType(_ generatedType: GeneratedTypeIR, validationProfile: ValidationProfile) -> [String] {
        switch generatedType.kind {
        case .bodyPayload:
            return emitStruct(
                name: generatedType.swiftTypeName,
                protocols: ["SOAPBodyPayload", "Equatable"],
                fields: generatedType.fields,
                validationProfile: validationProfile
            )
        case .faultDetailPayload:
            return emitStruct(
                name: generatedType.swiftTypeName,
                protocols: ["SOAPFaultDetailPayload", "Equatable"],
                fields: generatedType.fields,
                validationProfile: validationProfile
            )
        case .schemaModel:
            return emitStruct(
                name: generatedType.swiftTypeName,
                protocols: ["Codable", "Sendable", "Equatable"],
                fields: generatedType.fields,
                validationProfile: validationProfile
            )
        case .enumeration:
            return emitEnumType(generatedType)
        }
    }

    private func emitEnumType(_ generatedType: GeneratedTypeIR) -> [String] {
        var lines: [String] = []
        lines.append("public enum \(generatedType.swiftTypeName): String, Codable, Sendable, Equatable {")
        for rawValue in generatedType.enumerationCases {
            let caseName = sanitizeEnumCaseName(rawValue)
            if caseName == rawValue {
                lines.append("    case \(caseName)")
            } else {
                lines.append("    case \(caseName) = \"\(rawValue)\"")
            }
        }
        lines.append("}")
        return lines
    }

    // swiftlint:disable:next function_body_length
    private func emitStruct(
        name: String,
        protocols: [String],
        fields: [GeneratedTypeFieldIR],
        validationProfile: ValidationProfile
    ) -> [String] {
        var lines: [String] = []
        let orderedFields = fields.sorted { lhs, rhs in
            switch (lhs.xmlOrder, rhs.xmlOrder) {
            case let (lhsOrder?, rhsOrder?): return lhsOrder < rhsOrder
            default: return false
            }
        }

        let needsCodingKeys = orderedFields.contains { field in
            guard let xmlName = field.xmlName else { return false }
            return xmlName != field.name
        }

        lines.append("public struct \(name): \(protocols.joined(separator: ", ")) {")

        if orderedFields.isEmpty {
            lines.append("    public init() {}")
            lines.append("}")
            return lines
        }

        for field in orderedFields {
            let optionalSuffix = field.isOptional ? "?" : ""
            lines.append("    public var \(field.name): \(field.swiftTypeName)\(optionalSuffix)")
        }

        if needsCodingKeys {
            lines.append("")
            lines.append("    public enum CodingKeys: String, CodingKey {")
            for field in orderedFields {
                let xmlName = field.xmlName ?? field.name
                if xmlName != field.name {
                    lines.append("        case \(field.name) = \"\(xmlName)\"")
                } else {
                    lines.append("        case \(field.name)")
                }
            }
            lines.append("    }")
        }

        let initializerSignature = orderedFields
            .map { field -> String in
                let optionalSuffix = field.isOptional ? "?" : ""
                return "\(field.name): \(field.swiftTypeName)\(optionalSuffix)"
            }
            .joined(separator: ", ")
        lines.append("")
        lines.append("    public init(\(initializerSignature)) {")
        for field in orderedFields {
            lines.append("        self.\(field.name) = \(field.name)")
        }
        lines.append("    }")

        if validationProfile == .strict {
            let constrainedFields = orderedFields.filter { !$0.constraints.isEmpty }
            if !constrainedFields.isEmpty {
                lines.append("")
                lines.append("    /// Validates field constraints derived from XSD facets.")
                lines.append("    /// - Throws: `SOAPSemanticValidationError` on constraint violation.")
                lines.append("    public func validate() throws {")
                for field in constrainedFields {
                    lines.append(contentsOf: emitFieldValidation(field: field))
                }
                lines.append("    }")
            }
        }

        lines.append("}")
        return lines
    }

    private func emitFieldValidation(field: GeneratedTypeFieldIR) -> [String] {
        var lines: [String] = []
        let access = field.isOptional ? "\(field.name).map { $0 }" : "\(field.name)"
        _ = access
        for constraint in field.constraints {
            switch constraint.kind {
            case .minLength:
                let check = field.isOptional
                    ? "if let v = \(field.name), v.count < \(constraint.value)"
                    : "if \(field.name).count < \(constraint.value)"
                lines.append("        \(check) {")
                lines.append("            throw SOAPSemanticValidationError(field: \"\(field.name)\", code: \"[CG_SEMANTIC_001]\", message: \"Value is shorter than minLength \(constraint.value).\")")
                lines.append("        }")
            case .maxLength:
                let check = field.isOptional
                    ? "if let v = \(field.name), v.count > \(constraint.value)"
                    : "if \(field.name).count > \(constraint.value)"
                lines.append("        \(check) {")
                lines.append("            throw SOAPSemanticValidationError(field: \"\(field.name)\", code: \"[CG_SEMANTIC_002]\", message: \"Value exceeds maxLength \(constraint.value).\")")
                lines.append("        }")
            case .length:
                let check = field.isOptional
                    ? "if let v = \(field.name), v.count != \(constraint.value)"
                    : "if \(field.name).count != \(constraint.value)"
                lines.append("        \(check) {")
                lines.append("            throw SOAPSemanticValidationError(field: \"\(field.name)\", code: \"[CG_SEMANTIC_003]\", message: \"Value length must be exactly \(constraint.value).\")")
                lines.append("        }")
            case .pattern:
                let src = field.isOptional ? "\(field.name) ?? \"\"" : "\(field.name)"
                lines.append("        if (try? NSRegularExpression(pattern: \"\(constraint.value)\"))?.firstMatch(in: \(src), range: NSRange(\(src).startIndex..., in: \(src))) == nil {")
                lines.append("            throw SOAPSemanticValidationError(field: \"\(field.name)\", code: \"[CG_SEMANTIC_004]\", message: \"Value does not match pattern \\\"\(constraint.value)\\\".\")")
                lines.append("        }")
            default:
                break
            }
        }
        return lines
    }

    private func sanitizeEnumCaseName(_ rawValue: String) -> String {
        let tokens = rawValue
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber })
            .map(String.init)
            .filter { !$0.isEmpty }
        guard !tokens.isEmpty else { return "unknown" }
        var result = tokens[0].prefix(1).lowercased() + tokens[0].dropFirst()
        if tokens.count > 1 {
            for token in tokens.dropFirst() {
                result += token.prefix(1).uppercased() + token.dropFirst().lowercased()
            }
        }
        if let first = result.first, first.isNumber {
            return "value\(result)"
        }
        let reserved: Set<String> = ["class", "struct", "enum", "protocol", "func", "let", "var", "extension", "default", "case"]
        if reserved.contains(result) {
            return "`\(result)`"
        }
        return result
    }

    private func emitOperationContract(_ operation: OperationIR) -> [String] {
        var lines: [String] = []
        lines.append("public struct \(operation.operationContractTypeName): SOAPBindingOperationContract {")
        lines.append("    public typealias RequestPayload = \(operation.requestPayloadTypeName)")
        lines.append("    public typealias ResponsePayload = \(operation.responsePayloadTypeName)")
        lines.append("    public typealias FaultDetailPayload = \(operation.faultDetailTypeName)")
        lines.append("")
        lines.append("    public static var operationIdentifier: SOAPOperationIdentifier {")
        lines.append("        SOAPOperationIdentifier(rawValue: \"\(operation.operationIdentifierRawValue)\")")
        lines.append("    }")
        lines.append("")

        if let soapAction = operation.soapAction {
            lines.append("    public static var soapAction: SOAPAction? {")
            lines.append("        SOAPAction(rawValue: \"\(soapAction)\")")
            lines.append("    }")
        } else {
            lines.append("    public static var soapAction: SOAPAction? { nil }")
        }

        lines.append("")
        lines.append("    public static var bindingMetadata: SOAPBindingMetadata {")
        lines.append("        SOAPBindingMetadata(")
        lines.append("            envelopeVersion: .\(operation.bindingMetadata.envelopeVersion.rawValue),")
        lines.append("            style: .\(operation.bindingMetadata.style.rawValue),")
        lines.append("            bodyUse: .\(operation.bindingMetadata.bodyUse.rawValue)")
        lines.append("        )")
        lines.append("    }")
        lines.append("}")

        return lines
    }

    private func emitAsyncClients(
        _ services: [ServiceIR],
        syntaxProfile: CodeGenerationSyntaxProfile
    ) -> [String] {
        var lines: [String] = []
        let throwsClause = throwsClause(syntaxProfile: syntaxProfile)
        let clientType = existentialType("SOAPClientAsync", syntaxProfile: syntaxProfile)

        for service in services {
            for port in service.ports {
                let clientTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)AsyncClient"
                lines.append("public struct \(clientTypeName): Sendable {")
                lines.append("    public let client: \(clientType)")
                lines.append("    public let endpointURL: URL")
                lines.append("")
                lines.append("    public init(client: \(clientType), endpointURL: URL) {")
                lines.append("        self.client = client")
                lines.append("        self.endpointURL = endpointURL")
                lines.append("    }")
                lines.append("")

                for operation in port.operations {
                    lines.append("    public func \(operation.swiftMethodName)(request: \(operation.requestPayloadTypeName)) async \(throwsClause) -> SOAPOperationResponse<\(operation.responsePayloadTypeName), \(operation.faultDetailTypeName)> {")
                    lines.append("        try \(operation.operationContractTypeName).validateBinding()")
                    lines.append("        return try await client.invoke(\(operation.operationContractTypeName).self, request: request, endpointURL: endpointURL)")
                    lines.append("    }")
                    lines.append("")
                }

                lines.append("}")
                lines.append("")
            }
        }

        return lines
    }

    private func emitNIOClients(
        _ services: [ServiceIR],
        syntaxProfile: CodeGenerationSyntaxProfile
    ) -> [String] {
        var lines: [String] = []
        let clientType = existentialType("SOAPClientNIO", syntaxProfile: syntaxProfile)

        for service in services {
            for port in service.ports {
                let clientTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)NIOClient"
                lines.append("public struct \(clientTypeName) {")
                lines.append("    public let client: \(clientType)")
                lines.append("    public let endpointURL: URL")
                lines.append("")
                lines.append("    public init(client: \(clientType), endpointURL: URL) {")
                lines.append("        self.client = client")
                lines.append("        self.endpointURL = endpointURL")
                lines.append("    }")
                lines.append("")

                for operation in port.operations {
                    lines.append("    public func \(operation.swiftMethodName)(request: \(operation.requestPayloadTypeName), on eventLoop: EventLoop) -> EventLoopFuture<SOAPOperationResponse<\(operation.responsePayloadTypeName), \(operation.faultDetailTypeName)>> {")
                    lines.append("        do {")
                    lines.append("            try \(operation.operationContractTypeName).validateBinding()")
                    lines.append("        } catch {")
                    lines.append("            return eventLoop.makeFailedFuture(error)")
                    lines.append("        }")
                    lines.append("        return client.invoke(\(operation.operationContractTypeName).self, request: request, endpointURL: endpointURL, on: eventLoop)")
                    lines.append("    }")
                    lines.append("")
                }

                lines.append("}")
                lines.append("")
            }
        }

        return lines
    }

    private func emitAsyncServers(
        _ services: [ServiceIR],
        syntaxProfile: CodeGenerationSyntaxProfile
    ) -> [String] {
        var lines: [String] = []
        let throwsClause = throwsClause(syntaxProfile: syntaxProfile)
        let implementationTypePrefix = existentialTypePrefix(syntaxProfile: syntaxProfile)
        let serverType = existentialType("SOAPServerAsync", syntaxProfile: syntaxProfile)

        for service in services {
            for port in service.ports {
                let protocolTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)AsyncService"
                let registrarTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)AsyncServerRegistrar"

                lines.append("public protocol \(protocolTypeName): Sendable {")
                for operation in port.operations {
                    lines.append("    func \(operation.swiftMethodName)(request: \(operation.requestPayloadTypeName)) async \(throwsClause) -> SOAPOperationResponse<\(operation.responsePayloadTypeName), \(operation.faultDetailTypeName)>")
                }
                lines.append("}")
                lines.append("")

                lines.append("public struct \(registrarTypeName): Sendable {")
                lines.append("    public let server: \(serverType)")
                lines.append("")
                lines.append("    public init(server: \(serverType)) {")
                lines.append("        self.server = server")
                lines.append("    }")
                lines.append("")
                lines.append("    public func register(implementation: \(implementationTypePrefix)\(protocolTypeName)) async \(throwsClause) {")

                for operation in port.operations {
                    lines.append("        try \(operation.operationContractTypeName).validateBinding()")
                    lines.append("        try await server.register(\(operation.operationContractTypeName).self) { request in")
                    lines.append("            try await implementation.\(operation.swiftMethodName)(request: request)")
                    lines.append("        }")
                }

                lines.append("    }")
                lines.append("}")
                lines.append("")
            }
        }

        return lines
    }

    private func emitNIOServers(
        _ services: [ServiceIR],
        syntaxProfile: CodeGenerationSyntaxProfile
    ) -> [String] {
        var lines: [String] = []
        let implementationTypePrefix = existentialTypePrefix(syntaxProfile: syntaxProfile)
        let serverType = existentialType("SOAPServerNIO", syntaxProfile: syntaxProfile)

        for service in services {
            for port in service.ports {
                let protocolTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)NIOService"
                let registrarTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)NIOServerRegistrar"

                lines.append("public protocol \(protocolTypeName) {")
                for operation in port.operations {
                    lines.append("    func \(operation.swiftMethodName)(request: \(operation.requestPayloadTypeName), on eventLoop: EventLoop) -> EventLoopFuture<SOAPOperationResponse<\(operation.responsePayloadTypeName), \(operation.faultDetailTypeName)>>")
                }
                lines.append("}")
                lines.append("")

                lines.append("public struct \(registrarTypeName) {")
                lines.append("    public let server: \(serverType)")
                lines.append("")
                lines.append("    public init(server: \(serverType)) {")
                lines.append("        self.server = server")
                lines.append("    }")
                lines.append("")
                lines.append("    public func register(implementation: \(implementationTypePrefix)\(protocolTypeName)) {")

                for operation in port.operations {
                    lines.append("        server.register(\(operation.operationContractTypeName).self) { request, eventLoop in")
                    lines.append("            do {")
                    lines.append("                try \(operation.operationContractTypeName).validateBinding()")
                    lines.append("            } catch {")
                    lines.append("                return eventLoop.makeFailedFuture(error)")
                    lines.append("            }")
                    lines.append("            return implementation.\(operation.swiftMethodName)(request: request, on: eventLoop)")
                    lines.append("        }")
                }

                lines.append("    }")
                lines.append("}")
                lines.append("")
            }
        }

        return lines
    }

    private func throwsClause(syntaxProfile: CodeGenerationSyntaxProfile) -> String {
        if syntaxProfile.useTypedThrowsAnyError {
            return "throws(any Error)"
        }
        return "throws"
    }

    private func existentialType(_ protocolName: String, syntaxProfile: CodeGenerationSyntaxProfile) -> String {
        "\(existentialTypePrefix(syntaxProfile: syntaxProfile))\(protocolName)"
    }

    private func existentialTypePrefix(syntaxProfile: CodeGenerationSyntaxProfile) -> String {
        syntaxProfile.useExistentialAny ? "any " : ""
    }
}
