import Foundation
// swiftlint:disable line_length

public protocol SwiftSourceEmitter {
    func emit(ir: SOAPCodeGenerationIR, syntaxProfile: CodeGenerationSyntaxProfile) -> String
}

public struct SwiftCodeEmitter: SwiftSourceEmitter {
    public init() {}

    public func emit(ir: SOAPCodeGenerationIR, syntaxProfile: CodeGenerationSyntaxProfile) -> String {
        var lines: [String] = []
        lines.append("import Foundation")
        lines.append("import SwiftSOAPCore")

        if ir.generationScope.contains(.client) {
            if ir.runtimeTargets.contains(.async) {
                lines.append("import SwiftSOAPClientAsync")
            }
            if ir.runtimeTargets.contains(.nio) {
                lines.append("import NIOCore")
                lines.append("import SwiftSOAPClientNIO")
            }
        }

        if ir.generationScope.contains(.server) {
            if ir.runtimeTargets.contains(.async) {
                lines.append("import SwiftSOAPServerAsync")
            }
            if ir.runtimeTargets.contains(.nio) {
                lines.append("import NIOCore")
                lines.append("import SwiftSOAPServerNIO")
            }
        }

        lines.append("")
        lines.append("// Generated by SwiftSOAPCodeGen. Do not edit manually.")
        lines.append("// Target Swift version: \(syntaxProfile.targetSwiftVersion.description)")
        lines.append("")

        for generatedType in ir.generatedTypes {
            lines.append(contentsOf: emitType(generatedType))
            lines.append("")
        }

        for service in ir.services {
            for port in service.ports {
                for operation in port.operations {
                    lines.append(contentsOf: emitOperationContract(operation))
                    lines.append("")
                }
            }
        }

        if ir.generationScope.contains(.client) {
            if ir.runtimeTargets.contains(.async) {
                lines.append(contentsOf: emitAsyncClients(ir.services, syntaxProfile: syntaxProfile))
                lines.append("")
            }

            if ir.runtimeTargets.contains(.nio) {
                lines.append(contentsOf: emitNIOClients(ir.services, syntaxProfile: syntaxProfile))
                lines.append("")
            }
        }

        if ir.generationScope.contains(.server) {
            if ir.runtimeTargets.contains(.async) {
                lines.append(contentsOf: emitAsyncServers(ir.services, syntaxProfile: syntaxProfile))
                lines.append("")
            }

            if ir.runtimeTargets.contains(.nio) {
                lines.append(contentsOf: emitNIOServers(ir.services, syntaxProfile: syntaxProfile))
                lines.append("")
            }
        }

        return lines.joined(separator: "\n")
    }

    private func emitType(_ generatedType: GeneratedTypeIR) -> [String] {
        switch generatedType.kind {
        case .bodyPayload:
            return emitStruct(
                name: generatedType.swiftTypeName,
                protocols: ["SOAPBodyPayload", "Equatable"],
                fields: generatedType.fields
            )
        case .faultDetailPayload:
            return emitStruct(
                name: generatedType.swiftTypeName,
                protocols: ["SOAPFaultDetailPayload", "Equatable"],
                fields: generatedType.fields
            )
        case .schemaModel:
            return emitStruct(
                name: generatedType.swiftTypeName,
                protocols: ["Codable", "Sendable", "Equatable"],
                fields: generatedType.fields
            )
        }
    }

    private func emitStruct(name: String, protocols: [String], fields: [GeneratedTypeFieldIR]) -> [String] {
        var lines: [String] = []
        lines.append("public struct \(name): \(protocols.joined(separator: ", ")) {")

        if fields.isEmpty {
            lines.append("    public init() {}")
            lines.append("}")
            return lines
        }

        for field in fields {
            let optionalSuffix = field.isOptional ? "?" : ""
            lines.append("    public var \(field.name): \(field.swiftTypeName)\(optionalSuffix)")
        }

        let initializerSignature = fields
            .map { field -> String in
                let optionalSuffix = field.isOptional ? "?" : ""
                return "\(field.name): \(field.swiftTypeName)\(optionalSuffix)"
            }
            .joined(separator: ", ")
        lines.append("")
        lines.append("    public init(\(initializerSignature)) {")
        for field in fields {
            lines.append("        self.\(field.name) = \(field.name)")
        }
        lines.append("    }")
        lines.append("}")

        return lines
    }

    private func emitOperationContract(_ operation: OperationIR) -> [String] {
        var lines: [String] = []
        lines.append("public struct \(operation.operationContractTypeName): SOAPBindingOperationContract {")
        lines.append("    public typealias RequestPayload = \(operation.requestPayloadTypeName)")
        lines.append("    public typealias ResponsePayload = \(operation.responsePayloadTypeName)")
        lines.append("    public typealias FaultDetailPayload = \(operation.faultDetailTypeName)")
        lines.append("")
        lines.append("    public static var operationIdentifier: SOAPOperationIdentifier {")
        lines.append("        SOAPOperationIdentifier(rawValue: \"\(operation.operationIdentifierRawValue)\")")
        lines.append("    }")
        lines.append("")

        if let soapAction = operation.soapAction {
            lines.append("    public static var soapAction: SOAPAction? {")
            lines.append("        SOAPAction(rawValue: \"\(soapAction)\")")
            lines.append("    }")
        } else {
            lines.append("    public static var soapAction: SOAPAction? { nil }")
        }

        lines.append("")
        lines.append("    public static var bindingMetadata: SOAPBindingMetadata {")
        lines.append("        SOAPBindingMetadata(")
        lines.append("            envelopeVersion: .\(operation.bindingMetadata.envelopeVersion.rawValue),")
        lines.append("            style: .\(operation.bindingMetadata.style.rawValue),")
        lines.append("            bodyUse: .\(operation.bindingMetadata.bodyUse.rawValue)")
        lines.append("        )")
        lines.append("    }")
        lines.append("}")

        return lines
    }

    private func emitAsyncClients(
        _ services: [ServiceIR],
        syntaxProfile: CodeGenerationSyntaxProfile
    ) -> [String] {
        var lines: [String] = []
        let throwsClause = throwsClause(syntaxProfile: syntaxProfile)
        let clientType = existentialType("SOAPClientAsync", syntaxProfile: syntaxProfile)

        for service in services {
            for port in service.ports {
                let clientTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)AsyncClient"
                lines.append("public struct \(clientTypeName): Sendable {")
                lines.append("    public let client: \(clientType)")
                lines.append("    public let endpointURL: URL")
                lines.append("")
                lines.append("    public init(client: \(clientType), endpointURL: URL) {")
                lines.append("        self.client = client")
                lines.append("        self.endpointURL = endpointURL")
                lines.append("    }")
                lines.append("")

                for operation in port.operations {
                    lines.append("    public func \(operation.swiftMethodName)(request: \(operation.requestPayloadTypeName)) async \(throwsClause) -> SOAPOperationResponse<\(operation.responsePayloadTypeName), \(operation.faultDetailTypeName)> {")
                    lines.append("        try \(operation.operationContractTypeName).validateBinding()")
                    lines.append("        return try await client.invoke(\(operation.operationContractTypeName).self, request: request, endpointURL: endpointURL)")
                    lines.append("    }")
                    lines.append("")
                }

                lines.append("}")
                lines.append("")
            }
        }

        return lines
    }

    private func emitNIOClients(
        _ services: [ServiceIR],
        syntaxProfile: CodeGenerationSyntaxProfile
    ) -> [String] {
        var lines: [String] = []
        let clientType = existentialType("SOAPClientNIO", syntaxProfile: syntaxProfile)

        for service in services {
            for port in service.ports {
                let clientTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)NIOClient"
                lines.append("public struct \(clientTypeName) {")
                lines.append("    public let client: \(clientType)")
                lines.append("    public let endpointURL: URL")
                lines.append("")
                lines.append("    public init(client: \(clientType), endpointURL: URL) {")
                lines.append("        self.client = client")
                lines.append("        self.endpointURL = endpointURL")
                lines.append("    }")
                lines.append("")

                for operation in port.operations {
                    lines.append("    public func \(operation.swiftMethodName)(request: \(operation.requestPayloadTypeName), on eventLoop: EventLoop) -> EventLoopFuture<SOAPOperationResponse<\(operation.responsePayloadTypeName), \(operation.faultDetailTypeName)>> {")
                    lines.append("        do {")
                    lines.append("            try \(operation.operationContractTypeName).validateBinding()")
                    lines.append("        } catch {")
                    lines.append("            return eventLoop.makeFailedFuture(error)")
                    lines.append("        }")
                    lines.append("        return client.invoke(\(operation.operationContractTypeName).self, request: request, endpointURL: endpointURL, on: eventLoop)")
                    lines.append("    }")
                    lines.append("")
                }

                lines.append("}")
                lines.append("")
            }
        }

        return lines
    }

    private func emitAsyncServers(
        _ services: [ServiceIR],
        syntaxProfile: CodeGenerationSyntaxProfile
    ) -> [String] {
        var lines: [String] = []
        let throwsClause = throwsClause(syntaxProfile: syntaxProfile)
        let implementationTypePrefix = existentialTypePrefix(syntaxProfile: syntaxProfile)
        let serverType = existentialType("SOAPServerAsync", syntaxProfile: syntaxProfile)

        for service in services {
            for port in service.ports {
                let protocolTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)AsyncService"
                let registrarTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)AsyncServerRegistrar"

                lines.append("public protocol \(protocolTypeName): Sendable {")
                for operation in port.operations {
                    lines.append("    func \(operation.swiftMethodName)(request: \(operation.requestPayloadTypeName)) async \(throwsClause) -> SOAPOperationResponse<\(operation.responsePayloadTypeName), \(operation.faultDetailTypeName)>")
                }
                lines.append("}")
                lines.append("")

                lines.append("public struct \(registrarTypeName): Sendable {")
                lines.append("    public let server: \(serverType)")
                lines.append("")
                lines.append("    public init(server: \(serverType)) {")
                lines.append("        self.server = server")
                lines.append("    }")
                lines.append("")
                lines.append("    public func register(implementation: \(implementationTypePrefix)\(protocolTypeName)) async \(throwsClause) {")

                for operation in port.operations {
                    lines.append("        try \(operation.operationContractTypeName).validateBinding()")
                    lines.append("        try await server.register(\(operation.operationContractTypeName).self) { request in")
                    lines.append("            try await implementation.\(operation.swiftMethodName)(request: request)")
                    lines.append("        }")
                }

                lines.append("    }")
                lines.append("}")
                lines.append("")
            }
        }

        return lines
    }

    private func emitNIOServers(
        _ services: [ServiceIR],
        syntaxProfile: CodeGenerationSyntaxProfile
    ) -> [String] {
        var lines: [String] = []
        let implementationTypePrefix = existentialTypePrefix(syntaxProfile: syntaxProfile)
        let serverType = existentialType("SOAPServerNIO", syntaxProfile: syntaxProfile)

        for service in services {
            for port in service.ports {
                let protocolTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)NIOService"
                let registrarTypeName = "\(service.swiftTypeName)\(port.swiftTypeName)NIOServerRegistrar"

                lines.append("public protocol \(protocolTypeName) {")
                for operation in port.operations {
                    lines.append("    func \(operation.swiftMethodName)(request: \(operation.requestPayloadTypeName), on eventLoop: EventLoop) -> EventLoopFuture<SOAPOperationResponse<\(operation.responsePayloadTypeName), \(operation.faultDetailTypeName)>>")
                }
                lines.append("}")
                lines.append("")

                lines.append("public struct \(registrarTypeName) {")
                lines.append("    public let server: \(serverType)")
                lines.append("")
                lines.append("    public init(server: \(serverType)) {")
                lines.append("        self.server = server")
                lines.append("    }")
                lines.append("")
                lines.append("    public func register(implementation: \(implementationTypePrefix)\(protocolTypeName)) {")

                for operation in port.operations {
                    lines.append("        server.register(\(operation.operationContractTypeName).self) { request, eventLoop in")
                    lines.append("            do {")
                    lines.append("                try \(operation.operationContractTypeName).validateBinding()")
                    lines.append("            } catch {")
                    lines.append("                return eventLoop.makeFailedFuture(error)")
                    lines.append("            }")
                    lines.append("            return implementation.\(operation.swiftMethodName)(request: request, on: eventLoop)")
                    lines.append("        }")
                }

                lines.append("    }")
                lines.append("}")
                lines.append("")
            }
        }

        return lines
    }

    private func throwsClause(syntaxProfile: CodeGenerationSyntaxProfile) -> String {
        if syntaxProfile.useTypedThrowsAnyError {
            return "throws(any Error)"
        }
        return "throws"
    }

    private func existentialType(_ protocolName: String, syntaxProfile: CodeGenerationSyntaxProfile) -> String {
        "\(existentialTypePrefix(syntaxProfile: syntaxProfile))\(protocolName)"
    }

    private func existentialTypePrefix(syntaxProfile: CodeGenerationSyntaxProfile) -> String {
        syntaxProfile.useExistentialAny ? "any " : ""
    }
}
