name: SwiftLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: lint
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Cache SwiftLint
        id: cache-swiftlint
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/swiftlint
          key: ${{ runner.os }}-swiftlint

      - name: Install SwiftLint
        if: steps.cache-swiftlint.outputs.cache-hit != 'true'
        run: brew install swiftlint

      - name: Run SwiftLint
        # Produces GitHub annotations inline in the PR code view
        run: swiftlint lint --reporter github-actions-logging
